// src/sampleData.ts
export const sampleData = {
    tracks: [
        {
            id: 1,
            title: 'Shape of You',
            artist: 'Ed Sheeran',
            duration: '3:53',
            genre: 'Pop',
            fileUrl: '/local/tracks/shape-of-you.mp3',
            streamUrl: '/local/stream/tracks/1',
            thumbnailUrl: '/local/thumbnails/shape-of-you.jpg',
            downloadUrl: '/local/tracks/shape-of-you-download.mp3',
            format: 'mp3',
            bitrate: '320kbps',
            size: '9.2MB',
        },
        {
            id: 2,
            title: 'Blinding Lights',
            artist: 'The Weeknd',
            duration: '3:20',
            genre: 'Pop/R&B',
            fileUrl: '/local/tracks/blinding-lights.mp3',
            streamUrl: '/local/stream/tracks/2',
            thumbnailUrl: '/local/thumbnails/blinding-lights.jpg',
            downloadUrl: '/local/tracks/blinding-lights-download.mp3',
            format: 'mp3',
            bitrate: '320kbps',
            size: '8.7MB',
        },
        {
            id: 3,
            title: 'Levitating',
            artist: 'Dua Lipa',
            duration: '3:23',
            genre: 'Pop',
            fileUrl: '/local/tracks/levitating.mp3',
            streamUrl: '/local/stream/tracks/3',
            thumbnailUrl: '/local/thumbnails/levitating.jpg',
            downloadUrl: '/local/tracks/levitating-download.mp3',
            format: 'mp3',
            bitrate: '320kbps',
            size: '8.5MB',
        },
        {
            id: 4,
            title: 'Good 4 U',
            artist: 'Olivia Rodrigo',
            duration: '2:58',
            genre: 'Pop/Rock',
            fileUrl: '/local/tracks/good-4-u.mp3',
            streamUrl: '/local/stream/tracks/4',
            thumbnailUrl: '/local/thumbnails/good-4-u.jpg',
            downloadUrl: '/local/tracks/good-4-u-download.mp3',
            format: 'mp3',
            bitrate: '320kbps',
            size: '7.9MB',
        },
    ],
    artists: [
        {
            id: 1,
            name: 'Ed Sheeran',
            genre: 'Pop',
            country: 'UK',
            profileImage: '/local/artists/ed-sheeran.jpg',
            socialLinks: {
                local: '/local/artists/ed-sheeran',
            },
        },
        {
            id: 2,
            name: 'The Weeknd',
            genre: 'Pop/R&B',
            country: 'Canada',
            profileImage: '/local/artists/the-weeknd.jpg',
            socialLinks: {
                local: '/local/artists/the-weeknd',
            },
        },
        {
            id: 3,
            name: 'Dua Lipa',
            genre: 'Pop',
            country: 'UK',
            profileImage: '/local/artists/dua-lipa.jpg',
            socialLinks: {
                local: '/local/artists/dua-lipa',
            },
        },
        {
            id: 4,
            name: 'Olivia Rodrigo',
            genre: 'Pop/Rock',
            country: 'USA',
            profileImage: '/local/artists/olivia-rodrigo.jpg',
            socialLinks: {
                local: '/local/artists/olivia-rodrigo',
            },
        },
    ],
    playlists: [
        {
            id: 1,
            name: 'Top Hits',
            tracks: [1, 2, 3],
            createdBy: 'admin',
            coverImage: '/local/playlists/top-hits.jpg',
            totalDuration: '11:36',
            trackCount: 3,
        },
        {
            id: 2,
            name: 'Chill Vibes',
            tracks: [3, 4],
            createdBy: 'admin',
            coverImage: '/local/playlists/chill-vibes.jpg',
            totalDuration: '6:21',
            trackCount: 2,
        },
    ],
};
